[project]
name = "doc-generation"
version = "0.1.0"
description = "Sphinx documentation generation for OpenSolid"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["opensolid>=0.6.0", "sphinx>=8.2.3", "sphinx-rtd-theme>=3.0.2"]
