- ignore: { name: "Eta reduce" }
- ignore: { name: "Avoid lambda" }
- ignore: { name: "Use <$>" }
- ignore: { name: "Replace case with maybe" }
- ignore: { name: "Replace case with fromMaybe" }
- ignore: { name: "Redundant $" }
- ignore: { name: "Avoid lambda using `infix`" }
- ignore: { name: "Use null" }
- ignore: { name: "Use uncurry" }
- ignore: { name: "Use foldr" }
- ignore: { name: "Use intercalate" }
- ignore: { name: "Use foldl" }
- ignore: { name: "Use mapM" }
