- ignore: {name: "Eta reduce"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Replace case with maybe"}
- ignore: {name: "Replace case with fromMaybe"}
- ignore: {name: "Redundant $"}
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Use null"}
