name:                opensolid
version:             0.1.0.0
github:              "ianmackenzie/opensolid"
license:             MPL-2.0
author:              "Ian Mackenzie"
maintainer:          "ian.e.mackenzie@gmail.com"
copyright:           "2023 Ian Mackenzie"

extra-source-files:
- README.md

synopsis: Open-source geometric modelling framework
category: Geometry
description: Please see the README on GitHub at <https://github.com/ianmackenzie/opensolid#readme>

dependencies:
- base >= 4.7 && < 5
- text
- text-show

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-signatures
- -Wmissing-exported-signatures
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wsafe

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- MultiParamTypeClasses
- FlexibleInstances
- FlexibleContexts
- UndecidableInstances
- RebindableSyntax
- MonoLocalBinds
- TypeFamilies
- StandaloneDeriving
- ExistentialQuantification
- StrictData
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- QualifiedDo
- OverloadedLabels
- DataKinds
- ScopedTypeVariables
- GADTs
- RoleAnnotations
- RankNTypes
- LexicalNegation
- ImportQualifiedPost
- TypeOperators
- StandaloneKindSignatures

library:
  source-dirs: src

executables:
  sandbox:
    main:                Main.hs
    source-dirs:         sandbox
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opensolid

tests:
  opensolid-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opensolid
