[project]
name = "opensolid"
version = "0.10.0"
requires-python = ">=3.14"
authors = [{ name = "Ian Mackenzie", email = "ian.e.mackenzie@gmail.com" }]
description = "An under-development 2D/3D CAD library"
readme = "README.rst"

[project.urls]
source = "https://github.com/ianmackenzie/opensolid"
documentation = "https://opensolid.github.io/docs/0.10.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["setuptools>=75.6.0"]

[tool.ty.rules]
blanket-ignore-comment = "error"
missing-type-argument = "error"
possibly-unresolved-reference = "error"
unsupported-dynamic-base = "error"
division-by-zero = "error"
possibly-missing-attribute = "error"
possibly-missing-import = "error"

[tool.ty.analysis]
strict-literal-narrowing = true

[tool.ruff.lint]
extend-select = ["ANN", "PYI", "PGH003"]
preview = true
