#!/bin/bash

set -euo pipefail

INIT_PY=opensolid-python/lib/src/opensolid/__init__.py

# Run the Python code generator executable to create __init__.py
cabal run opensolid-python
# Format __init__.py for readability
uvx ruff@0.16.0 format $INIT_PY
# Check __init__.py for linter errors
echo "Running ruff check..."
uvx ruff@0.16.0 check $INIT_PY
echo "Running ty..."
uvx ty@0.0.64 check $INIT_PY
echo "Running Zuban..."
uvx zuban@0.9.0 check --strict $INIT_PY
echo "Running mypy..."
uvx mypy@2.3.0 --strict $INIT_PY
echo "Running Pyrefly..."
uvx pyrefly@1.1.1 check --preset strict $INIT_PY
# Generate the opensolid-ffi.def file with all API functions listed
# (necessary for Windows builds)
# Use zero verbosity to disable "Configuration is affected by..." lines, already printed above
cabal run --verbose=0 generate-def-file
# Build the native shared library
# (on Windows, this uses the opensolid-ffi.def file generated above)
# Use zero verbosity to disable "Configuration is affected by..." lines, already printed above
cabal build --verbose=0 opensolid-ffi
# Copy the native shared library to beside __init__.py
# so that it can be loaded properly
cp $(find dist-newstyle -name "libopensolid-ffi.*") opensolid-python/lib/src/opensolid
