#!/bin/bash

set -euo pipefail

LC_ALL=C.UTF-8 uv --project opensolid-python/lib tool run --from sphinx sphinx-build --fail-on-warning opensolid-python/lib/docs/source/ opensolid-python/lib/docs/build/
