#!/bin/bash

set -euo pipefail

stack run opensolid-python > opensolid-python/opensolid/__init__.py
ruff format opensolid-python/opensolid/__init__.py
ruff check --select ALL --ignore D203 --ignore D213 --ignore N801 --ignore COM812 --ignore D101 --ignore D107 --ignore D102 opensolid-python/opensolid/__init__.py
# D102: Missing docstring in public method
