name: Publish

on: workflow_dispatch

jobs:
  pypi:
    name: PyPI
    runs-on: ubuntu-latest
    environment:
      name: publish-to-pypi
      url: http://pypi.org/p/opensolid
    permissions:
      id-token: write
    needs:
      - windows
      - linux
      - macos-x86
      - macos-arm64
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "*-wheel"
          path: dist
          merge-multiple: true
      - name: Publish wheels
        uses: pypa/gh-action-pypi-publish@release/v1
